name: "\U0001F41E Bug report"
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        - If you have a question about Project Outlawn, you can ask for help on our [Discord][chat].
        - Also consult the [Frequently Asked Questions][faq] for common issues and questions.
        - Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean.
        - Also make sure that you are using the latest available version of everything. (OS, Launcher etc..)
        - Otherwise, fill out the information below to the best of your ability. Thank you!

        [chat]: https://discord.gg/CS5GzFTVWr
        [faq]: https://github.com/Twig6943/ProjectOutlawn/blob/main/docs/faq.
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        Provide a clear and concise description of what the bug is.
        - If there are steps to reproduce, list them here.
        - If this is a visual issue, please attach a screenshot of the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Affected platform
      description: Is the problem with the launcher or with the server?
      options:
        - Launcher
        - Server
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # Device information
  - type: input
    attributes:
      label: Operating system
      description: Please list the OS you are using.
      placeholder: Windows/Linux (Wine).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: If you have any additional information for us, such as device logs or crash information, use the field below.
    validations:
      required: false
