name: Build Qt Project for Windows

on:
  workflow_dispatch:  # This enables manual trigger through the GitHub UI button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MinGW
      run: |
        sudo apt update
        sudo apt install -y mingw-w64

    - name: Set up Qt for Windows
      run: |
        sudo apt install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

    - name: Configure and Build with CMake (Release Mode)
      run: |
        cd ProjectOutlawn/launcher/RushedQTLauncher/
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Archive Windows Build
      run: |
        mkdir -p artifacts
        cp -r ProjectOutlawn/launcher/RushedQTLauncher/build/artifacts/* artifacts/

    - name: Upload Windows Build as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: artifacts
