name: Build Client 🌙

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      #- name: Install Visual Studio Build Tools
       # run: |
        #  choco install visualstudio2019buildtools --version=16.11.7 -y

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.4.1

      - name: Clone ProjectOutlawn
        run: git clone https://github.com/Twig6943/ProjectOutlawn.git

      - name: Build Client
        run: |
          cd ProjectOutlawn\src\Client
          cl /LD dllmain.cpp MinHook.x64.lib /link /OUT:dllmain.dll /IMPLIB:dllmain.lib
