name: Build QTLauncher

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ProjectOutlawn/launcher/QTLauncher/requirements.txt

      - name: Build using PyInstaller
        run: |
          cd ProjectOutlawn/launcher/QTLauncher
          pyinstaller main.py --onefile --distpath ./dist

      - name: Verify the build output
        run: |
          dir D:\a\ProjectOutlawn\ProjectOutlawn\ProjectOutlawn\launcher\QTLauncher\dist

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: QTLauncher-Build
          path: D:\a\ProjectOutlawn\ProjectOutlawn\ProjectOutlawn\launcher\QTLauncher\dist
