name: Build Launcher Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone ProjectOutlawn
        run: |
          git clone https://github.com/Twig6943/ProjectOutlawn.git
          cd ProjectOutlawn/launcher/QTLauncher

      - name: Install Qt
        run: |
          choco install qt6-base-dev -y
          echo "C:\Qt\6.*/msvc*/bin" >> $GITHUB_PATH  # Add Qt binaries to PATH

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyQt6 pyinstaller

      - name: Compile with PyInstaller
        run: |
          cd ProjectOutlawn/launcher/QTLauncher
          pyinstaller --onefile --windowed --name launcher launcher.py

      - name: List output files
        run: |
          dir /s ProjectOutlawn/launcher/QTLauncher/dist

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Launcher-Windows
          path: ProjectOutlawn/launcher/QTLauncher/dist/launcher.exe
