name: Build Windows Executable on Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install MinGW-w64 and dependencies
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 python3 python3-pip

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python Dependencies (Windows Target)
        run: |
          pip3 install --upgrade pip
          pip3 install PyQt5 pyinstaller

      - name: Cross-Compile with PyInstaller (MinGW-w64)
        run: |
          cd ProjectOutlawn/launcher/QTLauncher
          pyinstaller --onefile --windowed --name launcher.exe launcher.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Launcher-Windows
          path: ProjectOutlawn/launcher/QTLauncher/dist/launcher.exe
