name: Build Launcher for Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone ProjectOutlawn
        run: git clone https://github.com/Twig6943/ProjectOutlawn.git
        cd ProjectOutlawn
        cd launcher
        cd QTLauncher

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'

      - name: Install Dependencies
        run: pip install PyQt6 pyinstaller

      - name: Compile with PyInstaller
        run: |
          cd ProjectOutlawn/launcher/QTLauncher
          pyinstaller --onefile --windowed launcher.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Launcher-Windows
          path: ProjectOutlawn/launcher/QTLauncher/dist/launcher.exe
