name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone ProjectOutlawn
        run: git clone https://github.com/Twig6943/ProjectOutlawn.git

      - name: Install Qt
        run: |
          choco install qt6-base-dev -y
          echo "C:\Qt\6.*/msvc*/bin" | Out-File -Append -Encoding ASCII $env:GITHUB_PATH
          echo "C:\Qt\6.*/msvc*/lib" | Out-File -Append -Encoding ASCII $env:GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd ProjectOutlawn/launcher/src
          python -m pip install -r requirements.txt

      - name: Compile with PyInstaller
        run: |
          cd ProjectOutlawn/launcher/src
          pyinstaller --onefile --target-architecture x86_64 --icon=icon.ico --windowed main.py

      - name: Zip the Executable
        run: |
          Compress-Archive -Path D:\a\ProjectOutlawn\ProjectOutlawn\ProjectOutlawn\launcher\src\dist -DestinationPath D:\a\ProjectOutlawn\ProjectOutlawn\ProjectOutlawn\launcher\src\dist.zip

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Launcher-Windows
          path: D:\a\ProjectOutlawn\ProjectOutlawn\ProjectOutlawn\launcher\QTLauncher\dist.zip

