name: Build Server 🔥

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up MSVC Environment
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          echo "MSVC environment set up" >> "%GITHUB_ENV%"

      - name: Install CMake
        shell: powershell
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
          refreshenv
          cmake --version

      - name: Clone ProjectOutlawn
        run: git clone https://github.com/Twig6943/ProjectOutlawn.git

      - name: Build Server
        shell: cmd
        run: |
          cd ProjectOutlawn\src\Server
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022"
          cmake --build . --config Release

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: DLL
          path: ProjectOutlawn/src/Server/build/Release*

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: ProjectOutlawn/src/Server/build/Installer/Release*

      - name: Upload Launcher
        uses: actions/upload-artifact@v4
        with:
          name: Launcher
          path: ProjectOutlawn/src/Server/build/Launcher/Release*
